from time import sleep
from DemoWebShop.lib.library import Base

class Buy_product(Base):
    login_link_locator = ("xpath", "//a[.='Log in']")
    email_locator = ("id", "Email")
    password_locator = ("id", "Password")
    login_btn = ("xpath", "//input[@value='Log in']")
    books_locator = ("xpath", "//div[@class='title']/..//a[@href='/books']")
    product_locator = ("xpath", "//h2[@class='product-title']/../../../../..//a[.='Health Book']")
    add_cart_locator = ("id", "add-to-cart-button-22")
    shopping_cart_locator = ("xpath", "//span[.='Shopping cart']")
    check_box_btn = ("id", "termsofservice")
    check_out_btn = ("id", "checkout")
    continue_btn1 = ("xpath", "//div[@id='billing-buttons-container']//input[@type='button']")
    continue_btn2 = ("xpath", "//p[@class='back-link']/..//input[@class='button-1 new-address-next-step-button']")
    radio_btn = ("id", "shippingoption_1")
    continue_btn3 = ("xpath", "//input[@class='button-1 shipping-method-next-step-button']")
    radio_btn2 = ("id", "paymentmethod_0")
    continue_btn4 = ("xpath", "//input[@class='button-1 payment-method-next-step-button']")
    continue_btn5 = ("xpath", "//input[@class='button-1 payment-info-next-step-button']")
    confrom_btn = ("id", "confirm-order-buttons-container")
    logout_locator = ("xpath", "//li[.='Log out']")

    def buy_product(self, email, password):
        self.click_on_a_element(self.login_link_locator)
        self.send_keys_to_text_field(self.email_locator, email)
        self.send_keys_to_text_field(self.password_locator, password)
        self.click_on_a_element(self.login_btn)
        self.click_on_a_element(self.books_locator)
        self.click_on_a_element(self.product_locator)
        self.click_on_a_element(self.add_cart_locator)
        self.click_on_a_element(self.shopping_cart_locator)
        self.click_on_a_element(self.check_box_btn)
        self.click_on_a_element(self.check_out_btn)
        self.click_on_a_element(self.continue_btn1)
        sleep(3)
        self.click_on_a_element(self.continue_btn2)
        sleep(3)
        self.click_on_a_element(self.radio_btn)
        sleep(2)
        self.click_on_a_element(self.continue_btn3)
        sleep(2)
        self.click_on_a_element(self.radio_btn2)
        sleep(3)
        self.click_on_a_element(self.continue_btn4)
        sleep(2)
        self.click_on_a_element(self.continue_btn5)
        sleep(2)
        self.click_on_a_element(self.confrom_btn)
        sleep(2)
        self.click_on_a_element(self.logout_locator)


