from time import sleep
from DemoWebShop.lib.library import Base

class Wishlist(Base):
    login_link_locator = ("xpath", "//a[.='Log in']")
    email_locator = ("id", "Email")
    password_locator = ("id", "Password")
    login_btn = ("xpath", "//input[@value='Log in']")
    shoe_locotor = ("xpath", "//ul[@class='top-menu']/.//a[@href='/apparel-shoes']")
    select_locator=("id","products-pagesize")
    option_locator1=("xpath","//option[.='4']")
    option_locator2=("xpath","//option[.='8']")
    option_locator3=("xpath","//option[.='12']")
    product_locator=("xpath","//img[@alt='Picture of Blue and green Sneaker']")
    add_2_wishlist_locator=("id","add-to-wishlist-button-28")
    wishist_btn=("xpath","//a[.='Wishlist']")
    quantity_locator=("xpath","//span[.='Qty.:']/..//input[@type='text']")
    remove_cart_locator=("name","removefromcart")
    update_cart_locator=("name","updatecart")
    logout_locator=("xpath","//li[.='Log out']")

    def wishlist(self,email,password,text):
        self.click_on_a_element(self.login_link_locator)
        self.send_keys_to_text_field(self.email_locator, email)
        self.send_keys_to_text_field(self.password_locator, password)
        self.click_on_a_element(self.login_btn)
        self.click_on_a_element(self.shoe_locotor)
        self.select_a_option(self.select_locator,self.option_locator1)
        self.select_a_option(self.select_locator,self.option_locator2)
        self.select_a_option(self.select_locator,self.option_locator3)
        self.click_on_a_element(self.product_locator)
        self.click_on_a_element(self.add_2_wishlist_locator)
        sleep(3)
        self.click_on_a_element(self.wishist_btn)
        sleep(2)
        self.clear_on_a_element(self.quantity_locator)
        sleep(3)
        self.send_keys_to_text_field(self.quantity_locator,text)
        self.click_on_a_element(self.remove_cart_locator)
        self.click_on_a_element(self.update_cart_locator)
        self.click_on_a_element(self.logout_locator)